---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 69e101e2638158dc665de4a2fcd57020beb84cbb
    fabric8.io/iconUrl: img/icons/vertx.svg
    fabric8.io/git-branch: master
    prometheus.io/scrape: "true"
    prometheus.io/port: "9779"
  labels:
    expose: "true"
    app: catalog-service
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: com.redhat.coolstore
  name: catalog-service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: catalog-service
    provider: fabric8
    group: com.redhat.coolstore
