---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: 69e101e2638158dc665de4a2fcd57020beb84cbb
      fabric8.io/iconUrl: img/icons/vertx.svg
      fabric8.io/git-branch: master
      prometheus.io/scrape: "true"
      prometheus.io/port: "9779"
    labels:
      expose: "true"
      app: catalog-service
      provider: fabric8
      version: 1.0.0-SNAPSHOT
      group: com.redhat.coolstore
    name: catalog-service
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: catalog-service
      provider: fabric8
      group: com.redhat.coolstore
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      fabric8.io/git-commit: 69e101e2638158dc665de4a2fcd57020beb84cbb
      fabric8.io/iconUrl: img/icons/vertx.svg
      fabric8.io/git-branch: master
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=catalog-service&var-version=1.0.0-SNAPSHOT
    labels:
      app: catalog-service
      provider: fabric8
      version: 1.0.0-SNAPSHOT
      group: com.redhat.coolstore
    name: catalog-service
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: catalog-service
        provider: fabric8
        group: com.redhat.coolstore
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 69e101e2638158dc665de4a2fcd57020beb84cbb
          fabric8.io/iconUrl: img/icons/vertx.svg
          fabric8.io/git-branch: master
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=catalog-service&var-version=1.0.0-SNAPSHOT
        labels:
          app: catalog-service
          provider: fabric8
          version: 1.0.0-SNAPSHOT
          group: com.redhat.coolstore
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: catalog-service:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: vertx
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          securityContext:
            privileged: false
